# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Developing Cognition
email: james@developingcognition.com
description: >
  Developing Cognition: training, education and behavioural nudges for personal
  effectiveness, decision making, behavioural psychology, communication, and
  metacognition.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://developingcognition.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: /articles/:title/

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
